### ISSUE TITLE
the visualizer folder parameter has to end with "/"

### ISSUE THREAD

**Issue by cheng-li** [cheng-li/pyramid#1]
[chengli@fiji11 pyramid-0.1.0]$ python visualization/visualizer.py /huge1/people/chengli/projects/pyramid/archives/app3/ohsumed_20000/8/reports/train_reports
Traceback (most recent call last):
  File "visualization/visualizer.py", line 1624, in <module>
    main()
  File "visualization/visualizer.py", line 1602, in main
    f1 = open(directoryName + configName, 'r')
IOError: [Errno 2] No such file or directory: '/huge1/people/chengli/projects/pyramid/archives/app3/ohsumed_20000/8/reports/data_config.json'
[chengli@fiji11 pyramid-0.1.0]$ python visualization/visualizer.py /huge1/people/chengli/projects/pyramid/archives/app3/ohsumed_20000/8/reports/train_reports/
Json:/huge1/people/chengli/projects/pyramid/archives/app3/ohsumed_20000/8/reports/train_reports/report_1.json load successfully.

**Comment by forSale** [comment]
Solved?
