### ISSUE TITLE
Compilation Error "maven-assembly-plugin:2.5.5:single failed: user id '16779829' is too big ( > 2097151 )"

### ISSUE THREAD

**Issue by GilbertHeywood** [cheng-li/pyramid#20]
> [INFO] pyramid 0.12.6 ..................................... SUCCESS [  0.238 s]
> [INFO] phrase-count-plugin 1.0 ............................ SUCCESS [  4.893 s]
> [INFO] pyramid 0.12.6 ..................................... FAILURE [ 15.589 s]
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  20.851 s
> [INFO] Finished at: 2020-03-07T20:08:16-05:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.5.5:single (default) on project pyramid: Execution default of goal org.apache.maven.plugins:maven-assembly-plugin:2.5.5:single failed: user id '16779829' is too big ( > 2097151 ). -> [Help 1]

I have attached the error message. Do you know how to deal with it?

**Comment by cheng-li** [comment]
Hi

Thanks for reporting this new issue. I made a fix in the develop branch. Can you please pull the develop branch and re-compile and see if the problem is resolved?

Best,
Cheng

**Comment by GilbertHeywood** [comment]
I think I found the solution here https://stackoverflow.com/questions/30246705/mvn-failure-on-build. I added tarLongFileMode in core/pom.xml and now it works for me. Thx for ur quick response!

**Comment by cheng-li** [comment]
That's also how I fixed it.

I've released a new patch version with the fix 
https://github.com/cheng-li/pyramid/releases/tag/v0.12.7
