### ISSUE TITLE
How to get the predictions for the test samples

### ISSUE THREAD

**Issue by jagdeeppani** [cheng-li/pyramid#5]
In the output folder, model files are being saved. What do the model files contain? How to use them? 

How can we get the predictions for the test samples?

**Comment by cheng-li** [comment]
Hi @jagdeeppani 

In the latest release [v0.7.3](https://github.com/cheng-li/pyramid/releases/tag/v0.7.3), after the training is done, predictions on the training and test sets will be saved to `train_predictions.txt` and `test_predictions.txt` in the output folder.

The model file is a serialized version of the trained model. It contains all model parameters and can be loaded back to do prediction. For example, after training is done, you could set `train=false` and `test=true`, and the program will load back the trained model and make predictions on the test set. This way, you can apply the model to different or new test sets.

Currently, we do not expose APIs for users to do things other than making predictions. If you are interested in doing additional analysis with the model, please let us know your need.

**Comment by jagdeeppani** [comment]
Thank you cheng-li. Now I am able to get the train_predictions and test_predictions.
It would be helpful, if you can print the feature importance scores (or feature weights) to some file. This will help us to understand which features are useful.
