### ISSUE TITLE
Confidence scores of the Predictions

### ISSUE THREAD

**Issue by jagdeeppani** [cheng-li/pyramid#6]
Hi @cheng-li ,
Is it possible to save the confidence scores of the predictions i.e. for a test data point when a label subset is predicted what is the confidence (or probability) of that label subset. This will help us to identify the hard-to-classify data points.

Thanks in advance.

**Comment by zihaolucky** [comment]
Besides the feature itself, to get insights from the confidence of a classifier might be not as straightforward as simple thresholding its output, especially these classifiers that normalize its prediction score, such as Softmax.

**Comment by cheng-li** [comment]
Thanks for the suggestion. We'll add this function in next code release soon.

**Comment by cheng-li** [comment]
Hi @jagdeeppani 

We have released a [new version](https://github.com/cheng-li/pyramid/releases/tag/v0.7.7) with requested features. 

A simple description of the output format can be found [here](https://github.com/cheng-li/pyramid/wiki/CBM#prediction-results).

**Comment by jagdeeppani** [comment]
Thank you very much @cheng-li for the quick release. 👍
